### ISSUE TITLE
Supporting Cookie Parameter Types

### ISSUE THREAD

**Issue by ksg97031** [noir-cr/noir#152]
In Django, FastAPI, and Flask projects, you can receive cookie parameters, and cookies act as one of the input vectors for the API. Therefore, let's add support for cookie parameter types to the src/models/endpoint.cr model.

**Comment by hahwul** [comment]
Hello again @ksg97031 
I added the cookie type to the Param type. Currently, the available types are as follows.
 ```bash
"query", "json", "form", "header", "cookie"

# It would be good to consider file types later on as well.
````

When you provide the param_type as `cookie` during `Param.new()`, it will be created as a cookie type. I also made some improvements to the output format for this. (Please review the pull request #170 😉)

```crystal
Param.new(param, "", "cookie")
```

![](https://github.com/noir-cr/noir/assets/13212227/47f0bee5-740e-4db9-b21e-67fecc0fbea7)
*Basic Result*

![](https://github.com/noir-cr/noir/assets/13212227/e1c9bd63-f76c-444a-a404-c7131108b14a)
*JSON Result*
