### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by kingthorin** [noir-cr/noir#156]
I was going to just make a PR but then realized that I wasn't 100% sure what you were going for:

"♠️ Noir is an attack surface detector form source code."

> ♠️ Noir is an attack surface detector from source code.

or

> ♠️ Noir is an attack surface detector for source code.

**Comment by hahwul** [comment]
Hi @kingthorin 
Oops, there was a typo. You're right about the content you mentioned.
Currently, Noir has been identifying for endpoints not only in the source code, so a slight modification was made.

> ♠️ Noir is an attack surface detector that identifies endpoints by analyzing source code and specification documents.

If you have any better suggestions, feel free to recommend them :D
