### ISSUE TITLE
[go-gin] Groups paths are not getting prepended

### ISSUE THREAD

**Issue by k-sau** [noir-cr/noir#242]
Hi,

Current logic doesn't support group paths which leads to invalid path. Here is one example of grouping:

```
func addUserRoutes(rg *gin.RouterGroup) {
	users := rg.Group("/users")

	users.GET("/", func(c *gin.Context) {
		c.JSON(http.StatusOK, "users")
	})
	users.GET("/comments", func(c *gin.Context) {
		c.JSON(http.StatusOK, "users comments")
	})
	users.GET("/pictures", func(c *gin.Context) {
		c.JSON(http.StatusOK, "users pictures")
	})
}
```

Current output would be:
```
/
/comments
/pictures
```

Expected output should be:
```
/users/
/users/comments
/users/pictures
```

There can be group of group paths as well, for example:
```
users := rg.Group("/users")
profile := users.Group("/profile")

profile.GET("/pictures", func(c *gin.Context) {
		c.JSON(http.StatusOK, "users pictures")
	})
```

So now base path will become:
```
/users/profile/pictures
```

Ref: https://github.com/gin-gonic/examples/blob/master/group-routes/routes/users.go

**Comment by hahwul** [comment]
Hi @k-sau 
Thanks for letting us know! 
We're gonna roll up our sleeves and get this fixed ASAP. Appreciate your patience :D

**Comment by k-sau** [comment]
Thanks @hahwul for prioritizing this :)
